server:
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123qweasd
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org.springframework.web: debug
    org.springframework.security: debug

